// Loading
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';

// Manage Errors
export const LOG_ERROR = 'LOG_ERROR';

export const SET_CALL_BACK_LINK = 'SET_CALL_BACK_LINK';

export const SET_AUTHED_USER = 'SET_AUTHED_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const RECORD_STUDENT = 'RECORD_STUDENT';

export const FETCH_QUIZES = 'FETCH_QUIZES';
export const RECORD_QUIZ = 'RECORD_QUIZ';

export const FETCH_LEVEL_QUIZES = 'FETCH_LEVEL_QUIZES';
export const RECORD_LEVEL = 'RECORD_LEVEL';
export const FETCH_ALL_LEVELS = 'FETCH_ALL_LEVELS';

export const FETCH_NEW_LEVEL_DETAILS = 'FETCH_NEW_LEVEL_DETAILS';
export const FETCH_NEW_LEVEL_QUIZES = 'FETCH_NEW_LEVEL_QUIZES';

export const FETCH_HISTORY = 'FETCH_HISTORY';

export const ALTER_STUDENT_STATUS = 'ALTER_STUDENT_STATUS';

export const DELETE_QUIZ = 'DELETE_QUIZ';
