export const languages = Object.freeze({
  kn: {
    welcome: 'Ikaze kuri',
    description: 'Hitamo iteraniro rikunogeye mu materaniro ya',
    name: 'Amazina yose',
    phone: 'Nimero ya Telephone',
    address: 'Aho utuye',
    age: 'Imyaka',
    button: 'Kwemeza',
    bookedTitle: 'Ubusabwe bwawe bwakiriwe',
    success: 'Ubusabe bwawe bwakiriwe, mutegereze ubutumwa bugufi',
    booked: 'iyafashwe',
    available: 'ihari',
    seatsLeft: 'isigaye',
    error: 'Mwamajije kubitsa uno mwanya',
  },
  en: {
    welcome: 'Welcome to',
    description: 'Register here for',
    descriptionTwo: 'church services.',
    name: 'Full Names',
    phone: 'Phone Number',
    address: 'Home Address',
    age: 'Age',
    button: 'Register',
    bookedTitle: 'Booked Successfully',
    success:
      'The seat has been booked successfully, Kindly wait for a confirmation SMS',
    booked: 'booked',
    available: 'available',
    seatsLeft: 'seats left',
    error: 'You have already booked this service',
  },
});
